### ISSUE TITLE
PA Review: {Auth}

### ISSUE THREAD

**Issue by axadn** [axadn/SoundShroud#3]

**Comment by axadn** [comment]
Elliot, I believe this feature is complete.

**Comment by evhumphrey** [comment]
Hey Adan, make sure to have a Demo log in as well

**Comment by axadn** [comment]
Hey, I added a demo login and adjusted the styling.

**Comment by axadn** [comment]
Ok. I adjusted it.

**Comment by axadn** [comment]
Updated.

**Comment by evhumphrey** [comment]
I've submitted an issue #9 that you need to complete before I can mark this feature off. It has to do with restyling your site to make it look more appealing and professional, a crucial part of first impressions when a recruiter looks at your site
