### ISSUE TITLE
PA Review: {Hosting on Heroku}

### ISSUE THREAD

**Issue by axadn** [axadn/SoundShroud#4]

**Comment by axadn** [comment]
I have uploaded the project to Heroku. The link in the wiki is now working

**Comment by evhumphrey** [comment]
Awesome! I would make your heroku url more descriptive (perhaps soundshroud.herokuapp.com)

**Comment by axadn** [comment]
Thanks, I've changed the domain name.

**Comment by axadn** [comment]
It's now http://sound-shroud.herokuapp.com

**Comment by evhumphrey** [comment]
Cool! Make sure to update your README to point to the proper link

**Comment by axadn** [comment]
Thanks. I updated it.

**Comment by evhumphrey** [comment]
👍
