### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by evhumphrey** [axadn/SoundShroud#9]
Site (while functional) should be restyled. Right now, the balance is off, spacing doesn't look right, sizing is a bit off. 

I suggest resizing things, and adding padding/whitespace. It will make your design look more professional and appealing.
![form-idea](https://user-images.githubusercontent.com/6361824/30670911-412cb28a-9e19-11e7-87ff-986005bd471b.png)

For sources of inspiration, check out [dribbble.com](https://dribbble.com/) or [codepen.io](https://codepen.io/) and search 'form', 'login', 'sign up' or something similiar

**Comment by axadn** [comment]
Hey Elliot, I worked on the styling a lot for logging in as well as login errors and you can view it on Heroku.
